import Testing
import Foundation
@testable import SermonSetCore

@Suite(.serialized) @MainActor struct LocalServerTests {
    @Test(.enabled(if: ProcessInfo.processInfo.environment["SERMONSET_INTEGRATION_URL"] != nil))
    func nativeClientAgainstIsolatedWorker() async throws {
        let configuration = CommunityConfiguration(baseURL: URL(string: ProcessInfo.processInfo.environment["SERMONSET_INTEGRATION_URL"]!)!)
        let senderStore = SermonStore(configuration: .preview), receiverStore = SermonStore(configuration: .preview)
        let sender = CommunityController(store: senderStore,configuration: configuration,signer: MemoryDeviceIdentity(),session: URLSession(configuration: .ephemeral))
        let receiver = CommunityController(store: receiverStore,configuration: configuration,signer: MemoryDeviceIdentity(),session: URLSession(configuration: .ephemeral))
        try await sender.createAccount(displayName: "Core test sender")
        try await receiver.createAccount(displayName: "Core test recipient")
        let senderID = try #require(sender.account?.id)
        struct SessionBody: Encodable { var bootstrapSecret: String; var accountID: String }
        struct SessionReply: Decodable { var account: CommunityAccount; var csrfToken: String }
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        let secret = try String(contentsOf: root.appendingPathComponent("build/core-server/bootstrap.txt"),encoding: .utf8)
        var bootstrap = URLRequest(url: configuration.baseURL.appendingPathComponent("v1/web/session")); bootstrap.httpMethod = "POST"
        bootstrap.setValue(configuration.audience,forHTTPHeaderField: "Origin"); bootstrap.setValue("application/json",forHTTPHeaderField: "Content-Type")
        bootstrap.httpBody = try APIJSON.encoder.encode(SessionBody(bootstrapSecret: secret,accountID: senderID))
        let (bootstrapData,bootstrapResponse) = try await sender.client.session.data(for: bootstrap)
        #expect((bootstrapResponse as? HTTPURLResponse)?.statusCode == 200)
        _ = try APIJSON.decoder.decode(SessionReply.self,from: bootstrapData)
        try await sender.refreshAccount()
        #expect(sender.account?.roles.contains { $0.role == "admin" } == true)
        try await sender.refreshServerKeys(); try receiverStore.cacheServerKeys(senderStore.cachedServerKeys)
        let source = try #require(senderStore.audioURL(for: senderStore.audioAssets(for: senderStore.libraryEntries[0].id)[0]))
        var local = try await senderStore.importAudio(from: source,title: "Native client integration \(UUID())")
        local.preacher = "Test speaker"; local.primaryPassage = "John 1"; local.sermonType = .wisdom; try senderStore.updateSermon(local)
        let privateNote = try senderStore.addNote(sermonID: local.id,text: "PRIVATE-INTEGRATION-SENTINEL",time: 1)
        let queue = PublishingController(store: senderStore,community: sender,uploader: FakeUploader())
        let checklist = PublishChecklist(musicReviewed: true,prayerRequestsReviewed: true,childrenReviewed: true,privateTalkReviewed: true)
        let job = try queue.enqueue(sermonID: local.id,selection: PublishSelection(checklist: checklist),confirmed: true)
        await queue.process()
        let submitted = try #require(queue.jobs.first { $0.id == job.id })
        let publicationID = try #require(submitted.publicationID)
        let sermonID = try #require(submitted.communitySermonID)
        struct Moderate: Encodable { var targetType: String; var targetID: String; var action: String; var reason: String }
        let _: APIReceipt = try await sender.client.send("POST","/v1/moderation/actions",body: Moderate(targetType: "publication",targetID: publicationID,action: "approve",reason: "Isolated integration fixture"),key: UUID().uuidString)
        let sermon = try await sender.sermon(sermonID)
        #expect(sermon.state == "published")
        #expect(!sermon.audioAvailable)
        #expect(sermon.summary == nil)
        try await sender.keep(sermonID)
        let card = try #require(sender.cards.first { $0.sermonID == sermonID })
        let operationID = UUID()
        let first = try await sender.createOffer(cardID: card.id,kind: .gift,operationID: operationID)
        let repeated = try await sender.createOffer(cardID: card.id,kind: .gift,operationID: operationID)
        #expect(first == repeated)
        let grant = try ServiceTokenVerifier(keys: senderStore.cachedServerKeys,audience: configuration.audience).verifyOffer(first.token)
        #expect(grant.offerID == first.offerID)
        let preview = try await receiver.previewOffer(id: nil,token: first.token)
        #expect(preview.card.id == card.id)
        try await receiver.acceptOffer(first.offerID,token: first.token)
        try await receiver.acceptOffer(first.offerID,token: first.token)
        await sender.refresh()
        #expect(!sender.cards.contains { $0.id == card.id })
        #expect(receiver.cards.filter { $0.id == card.id }.count == 1)
        #expect(senderStore.notes(for: local.id).map(\.id) == [privateNote.id])
        #expect(senderStore.isInLibrary(local.id))
        #expect(senderStore.isInLibrary(senderStore.localCommunityID(sermonID,server: configuration.audience)))
        #expect(receiverStore.notes(for: receiverStore.localCommunityID(sermonID,server: configuration.audience)).isEmpty)
        // A swap changes only owned instances; both local histories remain.
        var secondLocal = local; secondLocal.title = "Native swap fixture \(UUID())"; try senderStore.updateSermon(secondLocal)
        let secondPayload = try senderStore.buildPublishRequest(sermonID: local.id,selection: PublishSelection(checklist: checklist),audience: configuration.audience)
        struct PublishReply: Decodable { var publicationID: String; var sermonID: String; var audioAssetID: String?; var uploadURL: URL? }
        let second: PublishReply = try await sender.client.send("POST","/v1/publications",body: secondPayload,key: UUID().uuidString)
        let _: APIReceipt = try await sender.client.send("POST","/v1/moderation/actions",body: Moderate(targetType: "publication",targetID: second.publicationID,action: "approve",reason: "Swap fixture"),key: UUID().uuidString)
        try await sender.keep(second.sermonID)
        let swapCard = try #require(sender.cards.first { $0.sermonID == second.sermonID })
        let swap = try await sender.createOffer(cardID: swapCard.id,kind: .swap)
        try await receiver.proposeSwap(swap.offerID,cardID: card.id,token: swap.token)
        try await sender.confirmOffer(swap.offerID); try await sender.confirmOffer(swap.offerID)
        await receiver.refresh()
        #expect(sender.cards.contains { $0.id == card.id })
        #expect(receiver.cards.contains { $0.id == swapCard.id })
        #expect(senderStore.isInLibrary(senderStore.localCommunityID(second.sermonID,server: configuration.audience)))
        #expect(receiverStore.isInLibrary(receiverStore.localCommunityID(sermonID,server: configuration.audience)))
        // Verified church service QR enables only a trimmed enhanced upload, never the original.
        struct Claim: Encodable { var name: String; var website: String; var role: String; var evidence: String }
        struct ClaimReply: Decodable { var claimID: String }
        let churchName = "Core fixture church \(UUID())"
        let claim: ClaimReply = try await sender.client.send("POST","/v1/church-claims",body: Claim(name: churchName,website: "https://example.invalid",role: "Test staff",evidence: "Local test fixture only"),key: UUID().uuidString)
        let _: APIReceipt = try await sender.client.send("POST","/v1/moderation/actions",body: Moderate(targetType: "claim",targetID: claim.claimID,action: "approve",reason: "Local fixture"),key: UUID().uuidString)
        let managed: [CommunityChurch] = try await sender.client.page("/v1/portal/churches")
        let church = try #require(managed.first { $0.name == churchName })
        struct ServiceBody: Encodable { var service: String; var startsAt: Date; var recordingAllowed: Bool; var publicSharingAllowed: Bool; var reviewRequired: Bool; var expiresAt: Date }
        struct ServiceReply: Decodable { var serviceID: String; var token: String }
        let service: ServiceReply = try await sender.client.send("POST","/v1/portal/churches/"+church.id+"/services",body: ServiceBody(service: "Test service",startsAt: local.serviceDate,recordingAllowed: true,publicSharingAllowed: true,reviewRequired: false,expiresAt: Date.now.addingTimeInterval(7200)),key: UUID().uuidString)
        let serviceGrant = try senderStore.verifyServiceToken(service.token,audience: configuration.audience)
        #expect(serviceGrant.publicSharingAllowed)
        let original = try #require(local.canonicalAudioAssetID)
        try senderStore.setTrimWindow(AudioTrimWindow(start: 0,end: 3),for: original)
        let enhanced = try await senderStore.renderVoiceFocus(sermonID: local.id)
        let audioPayload = try senderStore.buildPublishRequest(sermonID: local.id,selection: PublishSelection(audioAssetID: enhanced.id,churchID: church.id,service: "Test service",rightsBasis: .serviceQR,serviceToken: service.token,checklist: checklist),audience: configuration.audience)
        let audioPublication: PublishReply = try await sender.client.send("POST","/v1/publications",body: audioPayload,key: UUID().uuidString)
        let upload = try #require(audioPublication.uploadURL), audioFile = try #require(senderStore.audioURL(for: enhanced))
        var uploadRequest = URLRequest(url: upload); uploadRequest.httpMethod = "PUT"; uploadRequest.setValue("audio/mp4",forHTTPHeaderField: "Content-Type")
        let (_,uploadResponse) = try await sender.client.session.upload(for: uploadRequest,fromFile: audioFile)
        #expect((uploadResponse as? HTTPURLResponse)?.statusCode == 200)
        let _: APIReceipt = try await sender.client.send("POST","/v1/publications/"+audioPublication.publicationID+"/complete",body: EmptyBody(),key: UUID().uuidString)
        let authorized = try await sender.audioURL(sermonID: audioPublication.sermonID)
        let (audioData,audioResponse) = try await sender.client.session.data(from: authorized.url)
        #expect((audioResponse as? HTTPURLResponse)?.statusCode == 200)
        #expect(audioData.sha256Hex == enhanced.checksumSHA256)
        let player = PlaybackController(store: senderStore)
        try await player.playCommunity(sermonID: audioPublication.sermonID,localID: senderStore.localCommunityID(audioPublication.sermonID,server: configuration.audience),community: sender)
        #expect(player.activeAssetID == senderStore.localCommunityID(authorized.audioAssetID,server: configuration.audience))
        let communityLocalID = senderStore.localCommunityID(audioPublication.sermonID,server: configuration.audience)
        let anchored = try senderStore.addMoment(sermonID: communityLocalID,audioAssetID: senderStore.localCommunityID(authorized.audioAssetID,server: configuration.audience),time: 0,note: "source anchor")
        let officialPayload = try senderStore.buildPublishRequest(sermonID: local.id,selection: PublishSelection(audioAssetID: enhanced.id,churchID: church.id,service: "Test service",rightsBasis: .official,checklist: checklist),audience: configuration.audience)
        let official: PublishReply = try await sender.client.send("POST","/v1/publications",body: officialPayload,key: UUID().uuidString)
        var officialRequest = URLRequest(url: try #require(official.uploadURL)); officialRequest.httpMethod = "PUT"; officialRequest.setValue("audio/mp4",forHTTPHeaderField: "Content-Type")
        let (_,officialResponse) = try await sender.client.session.upload(for: officialRequest,fromFile: audioFile)
        #expect((officialResponse as? HTTPURLResponse)?.statusCode == 200)
        let _: APIReceipt = try await sender.client.send("POST","/v1/publications/"+official.publicationID+"/complete",body: EmptyBody(),key: UUID().uuidString)
        #expect(official.sermonID == audioPublication.sermonID)
        await #expect(throws: SermonSetError.self) { try await player.playCommunity(sermonID: official.sermonID,localID: communityLocalID,community: sender) }
        try await player.useOfficialAudio(true)
        #expect(player.usingOfficialAudio)
        #expect(player.alignment == .unavailable)
        #expect(senderStore.moments(for: communityLocalID).first?.audioAssetID == anchored.audioAssetID)
        player.stop()
        let png = try #require(Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a6xkAAAAASUVORK5CYII="))
        let share = try await sender.createShareLink(sermonID: sermonID,cardImagePNG: png)
        let (_,shareResponse) = try await sender.client.session.data(from: share)
        #expect((shareResponse as? HTTPURLResponse)?.statusCode == 200)
        let _: APIReceipt = try await sender.client.send("POST","/v1/portal/churches/"+church.id+"/services/"+service.serviceID+"/revoke",body: EmptyBody(),key: UUID().uuidString)
        #expect(try await sender.audioURL(sermonID: audioPublication.sermonID).alignmentWarning != nil)
        let (_,revoked) = try await sender.client.session.data(from: authorized.url)
        #expect((revoked as? HTTPURLResponse)?.statusCode == 410)
        #expect(senderStore.notes(for: local.id).first?.text == privateNote.text)
        await sender.refreshDiscover(); #expect(!sender.isOffline)
        try await sender.refreshAtlas(); await sender.refreshSundayPack()
        #expect(sender.pack != nil) // pool may include earlier isolated runs
        _ = try await receiver.report(target: .sermon,targetID: sermonID,reason: .wrongAttribution,details: "Isolated test report")
        try await receiver.block(accountID: senderID)
        #expect(receiver.blockedAccountIDs.contains(senderID))
        await #expect(throws: CommunityAPIError.self) { try await receiver.previewOffer(id: nil,token: first.token) }
        try await receiver.unblock(accountID: senderID)
        #expect(!receiver.blockedAccountIDs.contains(senderID))
        // Rights-gated audio fails while card/history stay usable.
        await #expect(throws: CommunityAPIError.self) { try await receiver.audioURL(sermonID: sermonID) }
        try await receiver.deleteAccount()
        #expect(receiver.account == nil)
        #expect(receiverStore.isInLibrary(receiverStore.localCommunityID(sermonID,server: configuration.audience)))
        try senderStore.document.validate(); try receiverStore.document.validate()
    }
}
